# Generated by omarchy-theme-set-templates. Do not edit by hand.
foreground              {{foreground}}
background              {{background}}
selection_foreground     {{background}}
selection_background     {{bright_foreground}}

cursor                  {{accent}}
cursor_text_color        {{background}}

url_color               {{accent}}

active_border_color     {{accent}}
inactive_border_color   {{muted}}
bell_border_color       {{red}}

active_tab_foreground   {{background}}
active_tab_background   {{accent}}
inactive_tab_foreground {{dark_foreground}}
inactive_tab_background {{dark_background}}
tab_bar_background      {{darker_background}}

# black
color0  {{dark_background}}
color8  {{muted}}

# red
color1  {{red}}
color9  {{bright_red}}

# green
color2  {{green}}
color10 {{bright_green}}

# yellow
color3  {{yellow}}
color11 {{bright_yellow}}

# blue
color4  {{blue}}
color12 {{bright_blue}}

# magenta
color5  {{magenta}}
color13 {{bright_magenta}}

# cyan
color6  {{cyan}}
color14 {{bright_cyan}}

# white
color7  {{foreground}}
color15 {{bright_foreground}}
