/* Generated by omarchy-theme-set-templates. Do not edit by hand. */
* {
    background:         {{background}};
    foreground:          {{foreground}};
    accent-col:          {{accent}};
    selection-col:       {{selection}};
    muted-col:           {{muted}};

    dark-background:     {{dark_background}};
    darker-background:   {{darker_background}};
    lighter-background:  {{lighter_background}};
    dark-foreground:      {{dark_foreground}};
    bright-foreground:    {{bright_foreground}};

    red:     {{red}};
    green:   {{green}};
    yellow:  {{yellow}};
    blue:    {{blue}};
    magenta: {{magenta}};
    cyan:    {{cyan}};
}
