# Generated by omarchy-theme-set-templates. Do not edit by hand.
#
#                       border              background          text                 indicator           child_border
client.focused          {{accent}}          {{accent}}          {{background}}       {{accent}}           {{accent}}
client.focused_inactive {{muted}}           {{muted}}           {{foreground}}       {{muted}}             {{muted}}
client.unfocused        {{dark_background}} {{dark_background}} {{dark_foreground}}  {{dark_background}}   {{dark_background}}
client.urgent           {{red}}             {{red}}             {{background}}       {{red}}               {{red}}
client.placeholder      {{dark_background}} {{dark_background}} {{dark_foreground}}  {{dark_background}}   {{dark_background}}
client.background       {{background}}
