/* Generated by omarchy-theme-set-templates. Do not edit by hand. */
@define-color background {{background}};
@define-color foreground {{foreground}};
@define-color accent {{accent}};
@define-color selection {{selection}};
@define-color muted {{muted}};

@define-color dark_background {{dark_background}};
@define-color darker_background {{darker_background}};
@define-color lighter_background {{lighter_background}};
@define-color dark_foreground {{dark_foreground}};
@define-color light_foreground {{light_foreground}};
@define-color bright_foreground {{bright_foreground}};

@define-color color_red {{red}};
@define-color color_green {{green}};
@define-color color_yellow {{yellow}};
@define-color color_blue {{blue}};
@define-color color_magenta {{magenta}};
@define-color color_cyan {{cyan}};
@define-color color_orange {{orange}};
@define-color color_brown {{brown}};

@define-color bright_red {{bright_red}};
@define-color bright_green {{bright_green}};
@define-color bright_yellow {{bright_yellow}};
@define-color bright_blue {{bright_blue}};
@define-color bright_magenta {{bright_magenta}};
@define-color bright_cyan {{bright_cyan}};
